# Generated by Django 4.1.1 on 2022-10-03 18:17

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[users.validators.document_validator], verbose_name='Documento'),
        ),
    ]
