version: '3.8'


services:
  bmrabbitmq:
    restart: always
    image: rabbitmq:3.9.22-management-alpine
    env_file:
      - ./.env
    ports:
      - 15672:15672
    volumes:
      - bm_rabbitmq_data:/var/lib/rabbitmq/
      - bm_rabbitmq_logs:/var/log/rabbitmq/

  bmdb:
    container_name: bmdb
    restart: always
    image: postgres:13.8-alpine3.16
    volumes:
      - bm_postgres_data:/var/lib/postgresql/data/
      - /etc/bill_manager/docker/postgres/backups/:/backups/
      - /etc/bill_manager/docker/postgres/configs/postgresql.conf:/etc/postgres/config/postgresql.conf
      - bm_postgres_logs:/var/log/postgresql
    env_file:
      - ./.env
    command: postgres -c config_file=/etc/postgres/config/postgresql.conf -c logging_collector=on -c log_destination=stderr

  bmweb1:
    container_name: bmweb1

  bmworker1:
    container_name: bmworker



volumes:
  bm_rabbitmq_data:
  bm_rabbitmq_logs:
  bm_postgres_data:
  bm_postgres_logs: