#!/bin/bash  
#deve ser rodado de dentro da pasta docker/bashes
echo "Criando diretório de configurações..."
sudo mkdir /etc/bill_manager
sudo chmod 777 /etc/bill_manager
echo ""
echo ""
echo "Criando pasta para comprovantes de pagamento"
sudo mkdir -p /etc/bill_manager/media/payment_proofs
sudo chmod 777 /etc/bill_manager/media/payment_proofs
echo ""
echo ""
echo "Copiando pasta com arquivos do projeto para pasta criada..."
sudo cp -r docker /etc/bill_manager
echo ""
echo ""
echo "Copiando crontab..."
sudo cp bill_manager_crontab /etc/cron.d/bill_manager_crontab
echo ""
echo ""
echo "pronto."
