BILL_TYPES = (
    ('FIXED','FIXA'),
    ('INSTALLED','PARCELADA'),
    ('UNIQUE_INSTALLMENT','PARCELA ÚNICA')
)

BILL_STATUSES = (
    ('UNDEFINED','INDEFINIDO'),
    ('TO_EXPIRE','A VENCER'),
    ('EXPIRED','EXPIRADA'),
    ('WARNING','ATENÇÃO'),
    ('PAID','PAGA')
)