# Generated by Django 4.1.1 on 2022-10-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='value',
            field=models.FloatField(default=None, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
