# Generated by Django 4.1.1 on 2022-10-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_proof_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
