# Generated by Django 4.1.1 on 2022-10-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_bill_payment_proof_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='days_to_notify_before_expiration',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
