# Generated by Django 4.1.1 on 2022-10-03 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_alter_bill_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
