# Generated by Django 4.1.1 on 2022-10-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_alter_bill_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ('-created_date',), 'verbose_name': 'Conta', 'verbose_name_plural': 'Contas'},
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='installment_number',
            new_name='installment_sequence',
        ),
        migrations.AddField(
            model_name='bill',
            name='installment_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de parcelas'),
        ),
    ]
