# Generated by Django 4.1.1 on 2022-10-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_alter_bill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de pagamento'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='days_to_notify_before_expiration',
            field=models.IntegerField(verbose_name='Dias para notificar antes do vencimento'),
        ),
    ]
