# Generated by Django 4.1.1 on 2022-10-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_bill_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('MONEY', 'DINHEIRO'), ('DEBIT', 'DÉBITO'), ('CREDIT', 'CRÉDITO'), ('PIX', 'PIX'), ('ONLINE', 'ONLINE'), ('TRANSFER', 'TRANSFERÊNCIA')], max_length=18, null=True, verbose_name='Tipo de pagamento'),
        ),
    ]
