# Generated by Django 4.1.1 on 2022-10-05 13:32

import bills.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_bill_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='payment_proof_path',
            new_name='payment_proof_file_name',
        ),
        migrations.AlterField(
            model_name='bill',
            name='days_to_notify_before_expiration',
            field=models.IntegerField(validators=[bills.validators.only_positive_numbers], verbose_name='Dias para notificar antes do vencimento'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='installment_sequence',
            field=models.IntegerField(blank=True, null=True, validators=[bills.validators.only_greater_than_zero], verbose_name='Número da parcela'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='installment_total',
            field=models.IntegerField(blank=True, null=True, validators=[bills.validators.only_greater_than_zero], verbose_name='Quantidade de parcelas'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_date',
            field=models.DateField(blank=True, null=True, validators=[bills.validators.only_date_lower_or_equal_today], verbose_name='Data de pagamento'),
        ),
    ]
