# Generated by Django 4.1.1 on 2022-10-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_rename_payment_proof_path_bill_payment_proof_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='payment_proof_file_name',
        ),
    ]
