# Generated by Django 4.1.1 on 2022-10-05 16:44

import bills.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0013_remove_bill_payment_proof_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_proof_file',
            field=models.FileField(null=True, upload_to=bills.models.get_payment_proof_path, verbose_name='Comprovante de pagamento'),
        ),
    ]
