# Generated by Django 4.1.1 on 2022-10-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0016_alter_bill_payment_proof_file_alter_bill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('UNDEFINED', 'INDEFINIDO'), ('TO_EXPIRE', 'A VENCER'), ('EXPIRED', 'VENCIDA'), ('EXPIRES_TODAY', 'VENCE HOJE'), ('WARNING', 'ATENÇÃO'), ('PAID', 'PAGA')], default='UNDEFINED', max_length=13),
        ),
    ]
