# Generated by Django 4.1.1 on 2022-10-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0019_alter_bill_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('INSTALLED', 'PARCELADA'), ('UNIQUE_INSTALLMENT', 'PARCELA ÚNICA')], max_length=18, verbose_name='Tipo'),
        ),
    ]
