# Generated by Django 4.1.1 on 2022-10-06 19:28

import bills.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0020_alter_bill_bill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bank',
            field=models.CharField(blank=True, choices=[('BANCO_DO_BRASIL', 'Banco do Brasil'), ('BRADESCO', 'Bradesco'), ('CAIXA', 'Caixa'), ('ITAU', 'Itaú'), ('ITI', 'Iti'), ('MERCADO_PAGO', 'Mercado Pago'), ('NUBANK', 'Nubank'), ('PAG_SEGURO', 'Pag Seguro'), ('PAY_PAL', 'Pay Pal'), ('PIC_PAY', 'Pic Pay'), ('SANTANDER', 'Santander'), ('OTHER', 'Outro')], max_length=30, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('INSTALLED', 'Parcelada'), ('UNIQUE_INSTALLMENT', 'Parcela única')], max_length=18, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_date',
            field=models.DateField(default=bills.models.get_today_default_value, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='note',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('MONEY', 'Dinheiro'), ('DEBIT', 'Débito'), ('CREDIT', 'Crédito'), ('PIX', 'Pix'), ('ONLINE', 'Online'), ('TRANSFER', 'Transferência')], max_length=18, null=True, verbose_name='Tipo de pagamento'),
        ),
    ]
