# Generated by Django 4.1.1 on 2022-10-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0021_alter_bill_bank_alter_bill_bill_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('MONEY', 'Dinheiro'), ('DEBIT', 'Débito'), ('CREDIT', 'Crédito'), ('PIX', 'Pix'), ('ONLINE', 'Online'), ('TRANSFER', 'Transferência')], max_length=18, null=True, verbose_name='Forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('UNDEFINED', 'Indefinido'), ('TO_EXPIRE', 'A vencer'), ('EXPIRED', 'Vencida'), ('EXPIRES_TODAY', 'Vence hoje'), ('WARNING', 'Atenção'), ('PAID', 'Paga')], default='UNDEFINED', max_length=13),
        ),
    ]
