# Generated by Django 4.1.1 on 2022-10-07 02:47

import bills.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0023_alter_bill_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='days_to_notify_before_expiration',
            field=models.IntegerField(default=14, validators=[bills.validators.only_positive_numbers], verbose_name='Dias para notificar antes do vencimento'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='installment_sequence',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[bills.validators.only_greater_than_zero], verbose_name='Número da parcela'),
        ),
    ]
