# Generated by Django 4.1.1 on 2022-10-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0026_alter_bill_bank_alter_bill_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('INSTALLED', 'Parcelada'), ('UNIQUE_INSTALLMENT', 'Parcela Única')], max_length=18, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('UNDEFINED', 'Indefinido'), ('TO_EXPIRE', 'A Vencer'), ('EXPIRED', 'Vencida'), ('EXPIRES_TODAY', 'Vence Hoje'), ('WARNING', 'Atenção'), ('PAID', 'Paga')], default='UNDEFINED', max_length=13),
        ),
    ]
