# Generated by Django 4.1.1 on 2022-10-03 01:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bill_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billcategory',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterUniqueTogether(
            name='billcategory',
            unique_together={('name', 'user')},
        ),
    ]
