# Generated by Django 4.1.1 on 2022-10-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billrelatory',
            name='created_date',
        ),
    ]
